### ISSUE TITLE
@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2 doesn't provide typescript, requested by ts-node

### ISSUE THREAD

**Issue by lensbart** [EndemolShineGroup/cosmiconfig-typescript-loader#147]
See above

This warning gets shown when using Yarn 2, which is a bit more strict about subdependencies.

`typescript` is a peer dependency of `ts-node`, which is a dependency of `@endemolshinegroup/cosmiconfig-typescript-loader`. Typically it will already be installed in repositories consuming `cosmiconfig-typescript-loader`, but it should be included as a depencency (peer or otherwise) regardless.

**Comment by lensbart** [comment]
Warning can be suppressed by supplying the following in `.yarnrc.yml`:

```yml
packageExtensions:
  # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript:
        optional: true
```
